name: call-reusable-from-another-repo

on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  actions: read
  security-events: write
  packages: write

jobs:
  ci-pipeline-job:
    uses: skc949/reusablewf/.github/workflows/blank.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
