name: my-First-Workflow 

# TO get trigger on every push in this repo in any branch

on: 
 
  push:
jobs:
  job1:
   name: JOB1
   runs-on: ubuntu-latest 
   steps:
     - name: step1
       run: |
         pwd
         ls -ltr
         hostname 
     - name: step-2-Checkout 
       uses: actions/checkout@v5.0.0
     - name: step-3
       run: |
         pwd
         ls -ltr
         hostname 
