name: call-all-jobs

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline-job:
    uses: ./.github/workflows/All-jobs-reusable.yml
    secrets:
     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}