name: call-all-jobs

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
permissions:
  contents: read
  actions: read
  security-events: write
  packages: write
jobs:
  ci-pipeline-job:
    uses: ./.github/workflows/All-jobs-reusable.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
