
name: my-First-Workflow

# TO get trigger on every push in this repo in any branch

on:
  push:
    branches:
       -  dev
       - 'feature-*'
       - main 
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest

    steps:
      - name: step1
        run: |
          pwd
          ls -ltr
          hostname

      - name: step-2-Checkout
        uses: actions/checkout@v5.0.0

      - name: step-3
        run: |
          echo 'pwd' >> myartifact.txt
          mkdir artifacts
          echo 'ls -ltr' >> artifacts/lists.txt
          echo 'hostname' >> artifacts/hostname.txt

      - name: upload single file
        uses: actions/upload-artifact@v7
        with:
          name: single-file
          path: ./myartifact.txt

    

  job2:
    name: JOB2
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: checking current directory
        run: |
          pwd
          ls -ltr
          hostname

      - name: Download Single File artifact
        uses: actions/download-artifact@v7
        with:
          name: single-file
      - name: checking current directory post download
        run: |
          pwd
          ls -ltr
          hostname 
