name: self-hosted-runner
on:
 push:
    branches:
      - dev
jobs:
    demo-1:
        name: Dem_Job1
        runs-on: arc-demo 
        steps:
        - name: Display System Information 
          run: |
           echo "host Name : $(hostname)"
           echo "OS version:"
           lsb_release -a || cat  /etc/os-release 
           echo "Runner Name : ${{ runner.name}}"
           echo "Runner OS: ${{ runner.os }}"
           sleep 30
    demo-2:
        name: Dem_Job2
        runs-on: arc-demo # pick up self hosted runner with label 'self hosted'
        steps:
        - name: Display System Information 
          run: |
           echo "host Name : $(hostname)"
           echo "OS version:"
           lsb_release -a || cat  /etc/os-release 
           echo "Runner Name : ${{ runner.name}}"
           echo "Runner OS: ${{ runner.os }}"
           sleep 30